deploy:
  provider: firebase
  token:
    secure: "1//03BNCg5jGecRfCgYIARAAGAMSNwF-L9IrqvGv1VcfTUPdlOT_tF6MI3GT_Fnu-CaKeuF7zaInaQkoghErYl_uPUebvUHLpWIGBbI"
  branches:
  only:
    - master
  before_script:
    - npm install -g firebase-tools
  script:
    - ng build --prod
  after_success:
    - firebase deploy --token $FIREBASE_TOKEN
  notifications:
    email:
    on_failure: change
    on_success: change