language: node_js
node_js:
  - 8
branches:
  only:
    - master
before_script:
  - npm install -g firebase-tools
  - npm install jshint --save-dev
script:
  - jshint ./public/Tests/test.js
after_success:
  - firebase deploy --only hosting --token $FIREBASE_TOKEN