deploy:
  provider: firebase
  token:
    secure: "1//03BNCg5jGecRfCgYIARAAGAMSNwF-L9IrqvGv1VcfTUPdlOT_tF6MI3GT_Fnu-CaKeuF7zaInaQkoghErYl_uPUebvUHLpWIGBbI"
  skip_cleanup: true
sudo: true
language: node_js
node_js:
  - "10.15.3"
branches:
  only:
    - master
before_script:
  - npm install -g firebase-tools
script:
  - sh ./public/Tests/test.sh
after_success:
  - firebase deploy --token $FIREBASE_TOKEN